openapi: 3.1.0
info:
  title: ContractEase API
  version: 1.0.0
  description: API documentation for the ContractEase service
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.contract-ease.com
    description: Production server

components:
  schemas:
    Error:
      $ref: './schemas/Error.yaml'
    User:
      $ref: './schemas/User.yaml'
    SignUpRequest:
      $ref: './schemas/SignUpRequest.yaml'
    SignUpResponse:
      $ref: './schemas/SignUpResponse.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

security:
  - bearerAuth: []

paths:
  /api/health:
    $ref: './paths/health.yaml'
  /api/docs:
    get:
      summary: API Documentation
      description: Returns the API documentation UI
      operationId: getApiDocs
      responses:
        '200':
          description: Successfully returned API documentation
          content:
            text/html:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: './schemas/Error.yaml'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: './schemas/Error.yaml'
        '404':
          description: Documentation not found
          content:
            application/json:
              schema:
                $ref: './schemas/Error.yaml'
  /api/me:
    $ref: './paths/me.yaml'
  /api/auth/sign-up:
    $ref: './paths/auth.yaml'

