app:
  port: "8080"
  frontend_url: "http://client-contract-ease:5173"
  otel_endpoint: "http://openobserve:5080"

db:
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}
  port: ${DB_PORT}
  host: "postgres"
  schema: "public"

zitadel:
  issuer: ${ZITADEL_ISSUER_URL}
  client_id: ${ZITADEL_CLIENT_ID}
  client_secret: ${ZITADEL_CLIENT_SECRET}
  pat: ${ZITADEL_SERVICE_PAT}
