// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewDBTX creates a new instance of DBTX. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBTX(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBTX {
	mock := &DBTX{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DBTX is an autogenerated mock type for the DBTX type
type DBTX struct {
	mock.Mock
}

type DBTX_Expecter struct {
	mock *mock.Mock
}

func (_m *DBTX) EXPECT() *DBTX_Expecter {
	return &DBTX_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type DBTX
func (_mock *DBTX) Exec(context1 context.Context, s string, ifaceVals ...interface{}) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)); ok {
		return returnFunc(context1, s, ifaceVals...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgconn.CommandTag); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = returnFunc(context1, s, ifaceVals...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBTX_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type DBTX_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - context1
//   - s
//   - ifaceVals
func (_e *DBTX_Expecter) Exec(context1 interface{}, s interface{}, ifaceVals ...interface{}) *DBTX_Exec_Call {
	return &DBTX_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *DBTX_Exec_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *DBTX_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]interface{})
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *DBTX_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *DBTX_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *DBTX_Exec_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) (pgconn.CommandTag, error)) *DBTX_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type DBTX
func (_mock *DBTX) Query(context1 context.Context, s string, ifaceVals ...interface{}) (pgx.Rows, error) {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgx.Rows, error)); ok {
		return returnFunc(context1, s, ifaceVals...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Rows); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = returnFunc(context1, s, ifaceVals...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBTX_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type DBTX_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - context1
//   - s
//   - ifaceVals
func (_e *DBTX_Expecter) Query(context1 interface{}, s interface{}, ifaceVals ...interface{}) *DBTX_Query_Call {
	return &DBTX_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *DBTX_Query_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *DBTX_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]interface{})
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *DBTX_Query_Call) Return(rows pgx.Rows, err error) *DBTX_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *DBTX_Query_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) (pgx.Rows, error)) *DBTX_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type DBTX
func (_mock *DBTX) QueryRow(context1 context.Context, s string, ifaceVals ...interface{}) pgx.Row {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Row); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// DBTX_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type DBTX_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - context1
//   - s
//   - ifaceVals
func (_e *DBTX_Expecter) QueryRow(context1 interface{}, s interface{}, ifaceVals ...interface{}) *DBTX_QueryRow_Call {
	return &DBTX_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *DBTX_QueryRow_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *DBTX_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]interface{})
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *DBTX_QueryRow_Call) Return(row pgx.Row) *DBTX_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *DBTX_QueryRow_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) pgx.Row) *DBTX_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}
