// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Client struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID *uuid.UUID `json:"workspaceId"`
	Name        *string    `json:"name"`
	Email       *string    `json:"email"`
	Company     *string    `json:"company"`
	CreatedAt   *time.Time `json:"createdAt"`
}

type Contract struct {
	ID           uuid.UUID  `json:"id"`
	WorkspaceID  *uuid.UUID `json:"workspaceId"`
	ClientID     *uuid.UUID `json:"clientId"`
	CreatedBy    *uuid.UUID `json:"createdBy"`
	Title        string     `json:"title"`
	Content      *string    `json:"content"`
	Status       int16      `json:"status"`
	Version      *int32     `json:"version"`
	SentAt       *time.Time `json:"sentAt"`
	DraftPdfUrl  *string    `json:"draftPdfUrl"`
	SignedPdfUrl *string    `json:"signedPdfUrl"`
	CreatedAt    *time.Time `json:"createdAt"`
	UpdatedAt    *time.Time `json:"updatedAt"`
	DeletedAt    *time.Time `json:"deletedAt"`
}

type ContractSigningLink struct {
	ID         uuid.UUID  `json:"id"`
	ContractID *uuid.UUID `json:"contractId"`
	ClientID   *uuid.UUID `json:"clientId"`
	Token      string     `json:"token"`
	Status     int16      `json:"status"`
	CreatedAt  *time.Time `json:"createdAt"`
	ExpiresAt  *time.Time `json:"expiresAt"`
	OpenedAt   *time.Time `json:"openedAt"`
	SignedAt   *time.Time `json:"signedAt"`
}

type Signature struct {
	ID            uuid.UUID  `json:"id"`
	ContractID    *uuid.UUID `json:"contractId"`
	ClientID      *uuid.UUID `json:"clientId"`
	SignerName    *string    `json:"signerName"`
	SignerEmail   *string    `json:"signerEmail"`
	SignedAt      *time.Time `json:"signedAt"`
	IpAddress     *string    `json:"ipAddress"`
	UserAgent     *string    `json:"userAgent"`
	Method        *int16     `json:"method"`
	SignatureData *string    `json:"signatureData"`
	Consent       bool       `json:"consent"`
}

type User struct {
	ID        uuid.UUID  `json:"id"`
	ZitadelID string     `json:"zitadelId"`
	FirstName *string    `json:"firstName"`
	LastName  *string    `json:"lastName"`
	Username  *string    `json:"username"`
	Email     string     `json:"email"`
	CreatedAt *time.Time `json:"createdAt"`
}

type Workspace struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	OwnerID   *uuid.UUID `json:"ownerId"`
	CreatedAt *time.Time `json:"createdAt"`
}

type WorkspaceMember struct {
	UserID      uuid.UUID `json:"userId"`
	WorkspaceID uuid.UUID `json:"workspaceId"`
	Role        int16     `json:"role"`
}
