// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Client struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
	Name        *string    `json:"name"`
	Email       *string    `json:"email"`
	Company     *string    `json:"company"`
	CreatedAt   *time.Time `json:"created_at"`
}

type Contract struct {
	ID           uuid.UUID  `json:"id"`
	WorkspaceID  *uuid.UUID `json:"workspace_id"`
	ClientID     *uuid.UUID `json:"client_id"`
	CreatedBy    *uuid.UUID `json:"created_by"`
	Title        string     `json:"title"`
	Content      *string    `json:"content"`
	Status       int16      `json:"status"`
	Version      *int32     `json:"version"`
	SentAt       *time.Time `json:"sent_at"`
	DraftPdfUrl  *string    `json:"draft_pdf_url"`
	SignedPdfUrl *string    `json:"signed_pdf_url"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}

type ContractSigningLink struct {
	ID         uuid.UUID  `json:"id"`
	ContractID *uuid.UUID `json:"contract_id"`
	ClientID   *uuid.UUID `json:"client_id"`
	Token      string     `json:"token"`
	Status     int16      `json:"status"`
	CreatedAt  *time.Time `json:"created_at"`
	ExpiresAt  *time.Time `json:"expires_at"`
	OpenedAt   *time.Time `json:"opened_at"`
	SignedAt   *time.Time `json:"signed_at"`
}

type Signature struct {
	ID            uuid.UUID  `json:"id"`
	ContractID    *uuid.UUID `json:"contract_id"`
	ClientID      *uuid.UUID `json:"client_id"`
	SignerName    *string    `json:"signer_name"`
	SignerEmail   *string    `json:"signer_email"`
	SignedAt      *time.Time `json:"signed_at"`
	IpAddress     *string    `json:"ip_address"`
	UserAgent     *string    `json:"user_agent"`
	Method        *int16     `json:"method"`
	SignatureData *string    `json:"signature_data"`
	Consent       bool       `json:"consent"`
}

type User struct {
	ID        uuid.UUID  `json:"id"`
	ZitadelID string     `json:"zitadel_id"`
	FirstName *string    `json:"first_name"`
	LastName  *string    `json:"last_name"`
	Username  *string    `json:"username"`
	Email     string     `json:"email"`
	CreatedAt *time.Time `json:"created_at"`
}

type Workspace struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	OwnerID   *uuid.UUID `json:"owner_id"`
	CreatedAt *time.Time `json:"created_at"`
}

type WorkspaceMember struct {
	UserID      uuid.UUID `json:"user_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Role        int16     `json:"role"`
}
