// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (zitadel_id,
                   first_name,
                   last_name,
                   username,
                   email)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	ZitadelID string  `json:"zitadelId"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Username  *string `json:"username"`
	Email     string  `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ZitadelID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Email,
	)
	return err
}
