// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package repository

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (zitadel_id,
                   first_name,
                   last_name,
                   username,
                   email,
                   created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	ZitadelID string     `json:"zitadel_id"`
	FirstName *string    `json:"first_name"`
	LastName  *string    `json:"last_name"`
	Username  *string    `json:"username"`
	Email     string     `json:"email"`
	CreatedAt *time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ZitadelID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}
